version: "3.7"
services: 
  nestjs-server:
    build: 
      context: ./Docker01/Nest/.
      dockerfile: "/media/kirill/WindowsD/Programmieren/ProgramierHilfen/JavaScript/NESTjs/NESTinContainer/Docker01/Nest/Dockerfile"
    image: nestjs_lernen/nestjs-server
    hostname: nestjs-server
    container_name: nestjs-server
    restart: on-failure
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./code:/app
    depends_on: 
      - postgres-db
    networks: 
      nestjs_network:
        ipv4_address: 10.100.120.10
    command: [ "nest", "start", "--debug", "10.100.120.10:9229", "--watch" ] 

  angular-server:
    build: 
      context: ./Docker01/Angular/.
      dockerfile: "/media/kirill/WindowsD/Programmieren/ProgramierHilfen/JavaScript/NESTjs/NESTinContainer/Docker01/Angular/Dockerfile"
    image: nestjs_lernen/angular-server
    hostname: angular-server
    container_name: angular-server
    restart: on-failure
    ports:
      - "4200:4200"
    volumes:
      - ./code:/app
    depends_on: 
      - nestjs-server
    networks: 
      nestjs_network:
        ipv4_address: 10.100.120.20
    #command: [ /bin/bash ]

  postgres-db:
    build: 
      context: ./Docker01/Postgres/.
      dockerfile: "/media/kirill/WindowsD/Programmieren/ProgramierHilfen/JavaScript/NESTjs/NESTinContainer/Docker01/Postgres/Dockerfile"
    image: nestjs_lernen/postgres-db
    hostname: postgres-db
    container_name: postgres-db
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./code/pg-data:/var/lib/postgresql/data
    networks: 
      nestjs_network:
        ipv4_address: 10.100.120.30
    #command: [ /bin/bash ]

networks:
  nestjs_network:
      name: nestjs_network
      ipam: 
          driver: default
          config: 
              - subnet: "10.100.120.0/24"
  
