FROM node

WORKDIR /srv

RUN apt update && \
    apt -y dist-upgrade

RUN npm install -g @angular/cli

COPY ./entrypoint.sh /scripts/entrypoint.sh

VOLUME [ "/srv" ]

EXPOSE 4200

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD [ "ng", "serve", "--open", "--host", "0.0.0.0" ] 