FROM postgres

RUN apt update && \
    apt dist-upgrade

COPY ./createDB.sql /docker-entrypoint-initdb.d/createDB.sql

#RUN /bin/bash -c /docker-entrypoint-initdb.d/createDB.sql

VOLUME [ "/var/lib/postgresql" ]