source 'https://rubygems.org' # sagt, wo der Bunlder man nach den Gems suchen soll
    gem 'selenium-webdriver', '~> 3.142', '>= 3.142.3' #zu installiertenden Gem angeben
    gem 'rspec', '~> 3.8' # Bib für Assetions