FROM node

RUN apt update && \
    apt -y dist-upgrade

RUN apt-get -y install apt-transport-https ca-certificates

#yarn installieren
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt update && \
    apt install -y yarn

#install nest
RUN npm install -g @nestjs/cli && \
    echo "Die Version von Nest ist -> $(nest --version)"

#install synp
RUN npm install -g synp

COPY ./entrypoint.sh /scripts/entrypoint.sh
#COPY ./entrypoint.sh /app/scripts/nodemon-debug.json

VOLUME [ "/app/" ]

EXPOSE 3000 9229

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD [ "npm", "run", "start:debug" ] 