
GET https://reqres.in/api/users

#GET https://mor10.com

HEAD http://restful.dev/x/y/posts
Authorization: Basic username myPassword

OPTIONS http://restful.dev/x/y/posts
Authorization: Basic username myPassword

GET http://restful.dev/x/y/posts
Authorization: Basic username myPassword

GET http://restful.dev/x/y/posts?per_page=1
Authorization: Basic username myPassword