version: "3.7"
services: 
  redis-server:
    build: 
      context: ./DockerFiles/Redis-Server/
      dockerfile: /media/kirill/WindowsD/Programmieren/ONLINE-KURSE/Sonstiges/Redis/CodeBeispiele/DockerFiles/Redis-Server/Dockerfile
    image: redis_lernen/redis-server
    hostname: redis-server
    container_name: redis-server
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      lernen_network:
        ipv4_address: 10.200.0.10
    volumes:
      - .:/app/code/
  
  nodejs-redis-server:
    build:
      context: ./DockerFiles/NodeJS-Server/
      dockerfile: /media/kirill/WindowsD/Programmieren/ONLINE-KURSE/Sonstiges/Redis/CodeBeispiele/DockerFiles/NodeJS-Server/Dockerfile
    image: redis_lernen/nodejs-server
    hostname: nodejs-server
    container_name: nodejs-server
    restart: on-failure
    ports:
      - "8000:8000"
      - "8080:8080"
    networks: 
      lernen_network:
        ipv4_address: 10.200.0.11
    volumes:
      - .:/app/code

networks:
  lernen_network:
    name: lernen_network
    ipam:
      driver: default
      config: 
        - subnet: "10.200.0.0/24"
