version: "3"

services: 
    ts-node:
        build: 
            context: .
            dockerfile: "/media/kirill/WindowsD/Programmieren/ProgramierHilfen/JavaScript/TypeScript/typescript/dockerfile"
        image: ts-node
        hostname: ts-node
        container_name: ts-node
        restart: on-failure
        ports:
            - "9229:9229"
            - "3000:3000"
            - "8000:8000"
        volumes:
            - ./code:/srv
        command: [ "nop/ts-server", "tsc", "--watch", "--project", "tsconfig.json" ]
