from node

WORKDIR /srv

RUN apt update && \
    apt -y dist-upgrade

RUN npm install -g typescript

# RUN npm install -g commonjs systemjs @types/node rxjs

VOLUME [ "/srv" ]

EXPOSE 3000
EXPOSE 8000


COPY ./entrypoint.sh /scripts/entrypoint.sh

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

#CMD [ "tsc", "--watch", "--project", "tsconfig.json" ]

#! Dann sich in docker-container anmelden und in ./dist node XXX.js ausführen