version: "3.7"
services: 
  mongodb-server:
    build: 
      context: ./DockerFiles/MongoDB/
      dockerfile: /media/kirill/WindowsD/Programmieren/ONLINE-KURSE/Sonstiges/Learning MongoDB/DockerFiles/MongoDB/Dockerfile
    image: mongodb_lernen/mongo-server
    hostname: mongodb-server
    container_name: mongodb-server
    restart: on-failure
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    networks:
      lernen_network:
        ipv4_address: 10.200.0.20
    volumes:
      - .:/mongodb/code
  
  nodejs-server-mongo:
    build:
      context: ./DockerFiles/NodeJS-Server/
      dockerfile: /media/kirill/WindowsD/Programmieren/ONLINE-KURSE/Sonstiges/Learning MongoDB/DockerFiles/NodeJS-Server/Dockerfile
    image: mongodb_lernen/nodejs-server
    hostname: nodejs-server-mongo
    container_name: nodejs-server-mongo
    restart: on-failure
    ports:
      - "8000:8000"
      - "8080:8080"
    networks: 
      lernen_network:
        ipv4_address: 10.200.0.21
    volumes:
      - .:/app/code

networks:
  lernen_network:
    name: lernen_network
    ipam:
      driver: default
      config: 
        - subnet: "10.200.0.0/24"
