FROM node

WORKDIR /srv

RUN apt update && \
    apt -y dist-upgrade

RUN npm install -g @nestjs/cli

COPY ./entrypoint.sh /scripts/entrypoint.sh
#COPY ./entrypoint.sh /app/scripts/nodemon-debug.json

VOLUME [ "/srv" ]

EXPOSE 3000 9229

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD [ "npm", "run", "start:debug" ]